name: Manual Update (Backup)

on:  
  workflow_dispatch: # Залишили тільки ручний запуск кнопкою

jobs:
  run-parser:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod tidy

      - name: Run Go Parser
        run: go run main.go
        env:
          TZ: Europe/Kyiv

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # Додаємо всю папку data, де тепер лежать всі 12 файлів
          git add data/discos-*.ics
          git commit -m "Manual update via GitHub Actions: $(date +'%d.%m.%Y %H:%M')" || echo "No changes to commit"
          git push
