name: Hourly Schedule Update

concurrency:
  group: 'pages-${{ github.ref }}'
  cancel-in-progress: true

on:
  schedule:
    # Запуск кожної години у 00 хвилин (наприклад, 10:00, 11:00 і т.д.)
    - cron: '0 * * * *'
  workflow_dispatch: # Залишаємо можливість ручного запуску

jobs:
  run-parser:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod tidy

      - name: Run Go Parser
        run: go run main.go
        env:
          TZ: Europe/Kyiv

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # Додаємо всю папку data, де лежать файли
          git add data/discos-*.ics
          git commit -m "Scheduled update: $(date +'%d.%m.%Y %H:%M')" || echo "No changes to commit"
          git push
